[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/out"

[[redirects]]
  from = "/api/*"
  to   = "https://shivamshrivastava.onrender.com/:splat"
  status = 200
  force  = true