[build]
  command   = "npm install && npm run export"
  publish   = "frontend/out"

[[redirects]]
  from = "/api/*"
  to = "https://shivamshrivastava.onrender.com/:splat"
  status = 200
  force = true